name: Pull Salesforce Metadata, Run SCA PMD & Send File

on:
  push:
    branches:
    - master

jobs:
  send_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Get Salesforce OAuth2 Token
        id: get_token
        run: |
          CLIENT_ID=3MVG9n_HvETGhr3A7RsBhmC5FTKle1C59pGSGAIky.5sEsZQq04PtYyZ.tuz7Jl7KDmBZP9JQfipVnyOz.O0V
          CLIENT_SECRET=9F611F06C496C62C34C322D298F3599FAA2FE8D3812736900E048C9E5D263111
          USERNAME=assest1_codeninja@epam.com
          PASSWORD=asset@2025MQtJMCZeRMrLUyy25lvvvUKed
          TOKEN_RESPONSE=$(curl -d "grant_type=password" -d "client_id=$CLIENT_ID" -d "client_secret=$CLIENT_SECRET" -d "username=$USERNAME" -d "password=$PASSWORD" "https://login.salesforce.com/services/oauth2/token")
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          echo "access_token1=$ACCESS_TOKEN"  >> "$GITHUB_ENV"
      - name: Send File to Salesforces
        run: |
          FILE_PATH=ScannerResult.csv
          csv_file="$FILE_PATH"
          base64_string=$(base64 "$csv_file")
          base64_string=$(echo "$base64_string" | tr -d '\n')
          SALESFORCE_URL=https://epam-2e1-dev-ed.develop.my.salesforce.com/services/apexrest/uploadScanner
          ACCESS_TOKEN=$access_token1
          ruleEngine=pmd
          # # Use jq to create a JSON object
          # json_body=$(jq -n \
          #   --arg key1 $base64_string \
          #   --arg key2 $GITHUB_REPOSITORY \
          #   --arg key3 $ruleEngine \
          #   '{"base64_data": $key1, "repoName": $key2, "engine":$key3}')
          # responseScanner=$(curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" -d "$json_body" $SALESFORCE_URL)
          # echo "response-Scanner $responseScanner"
          # Save JSON data to a file
          echo "{\"base64_data\": \"$base64_string\", \"repoName\": \"$GITHUB_REPOSITORY\", \"engine\": \"$ruleEngine\"}" > json_body.json
          responseScanner=$(curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" -d "@json_body.json" $SALESFORCE_URL)
          echo "response-Scanner $responseScanner"
